declare let totalHourlyGrossPays: number;
declare let totalPieceWorkerGrossPays: number;
declare let totalCommissionGrossPays: number;
declare let totalSalariedGrossPays: number;
declare const hoursWorkedInput: HTMLInputElement;
declare const hourlyRateInput: HTMLInputElement;
declare const piecesMadeInput: HTMLInputElement;
declare const pricePerPieceInput: HTMLInputElement;
declare const salesAmountInput: HTMLInputElement;
declare const commissionPercentageInput: HTMLInputElement;
declare const salariedInput: HTMLInputElement;
declare const employeeTypeSelect: HTMLSelectElement;
declare const allFieldSets: HTMLFieldSetElement[];
declare const btnCalculate: HTMLButtonElement;
declare const btnClear: HTMLButtonElement;
declare const btnShowTotals: HTMLButtonElement;
declare const btnCloseModal: HTMLButtonElement;
declare const resultsPlaceholder: HTMLDivElement;
declare const resultsList: HTMLUListElement;
declare const errorMsg: HTMLParagraphElement;
declare const totalsModal: HTMLDivElement;
declare const grandTotal: HTMLElement;
declare function hideAllFieldSets(): void;
declare function showErrors(message: string): void;
declare function clearErrors(): void;
declare function formatToCurrency(amount: number): string;
declare function onEmployeeTypeChange(): void;
declare function appendResult(typeLabel: string, grossPay: number, message: string): void;
declare function refreshModalTotals(): void;
declare function onCalculate(): void;
declare function onClear(): void;
declare function openModal(): void;
declare function closeModal(): void;
//# sourceMappingURL=payroll.d.ts.map